sudo: false
language: node_js
node_js:
  - 12
cache: yarn
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_1eed37eae157_key -iv $encrypted_1eed37eae157_iv -in id_rsa.enc -out /.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 119.28.222.199\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - yarn install
script:
  - yarn build:prod
after_success:
  - mkdir dist
  - cp -r .next/ dist/.next
  - cp -r config/ dist/config
  - cp next.config.js package.json pm2.config.js dist
  - rsync -avzP --delete --exclude="node_modules" dist/ root@119.28.222.199:/data/www/nextjs-mobx-typescript
  - pm2 reload /data/www/nextjs-mobx-typescript/pm2.config.js
